
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.scripts.JO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tadeo Daniel
 */
public class conver extends javax.swing.JFrame {
op conv=new op();
///Tadeo checa el programa 
    /**
     * Creates new form conver
     */
    public conver() {
        initComponents();
                                     this.setLocationRelativeTo(null);
                                     /*Sistema Numerico[0]
Decimal[1]
Hexadecimal[2]
Octal[3]
Binario[4] */
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        v1 = new javax.swing.JTextField();
        v2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        v3 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Valor 1");

        jLabel2.setText("Valor 2");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistema Numerico", "Decimal", "Hexadecimal", "Octal", "Binario" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistema Numerico", "Decimal", "Hexadecimal", "Octal", "Binario" }));

        jLabel3.setText("Respuesta");

        v3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v3ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistema Numerico", "Decimal", "Hexadecimal", "Octal", "Binario" }));

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reiniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Sumar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Conv Respuesta");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 163, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, 1, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void v3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
/////Como usar lo seleccionas el tipo de valor decimal,octal... en el valor 2 y luego seleccionas
///el tipo de valo 1,lo que va a suceder es que el valor 1 se convertira en el mismo tipo de valor que es el valor 2 
//getText saca setText meter


try{
        if(jComboBox2.getSelectedItem().toString().equals("Octal")&&
                ( jComboBox1.getSelectedItem().toString().equals("Decimal"))){///decimal A octal 
    String Num=null;//FUNCIONA
  Num=v1.getText();
op CN=new op();
v1.setText(CN.intToOctal(new Integer(Num)));
 jComboBox1.setSelectedIndex(3);
 
 

 
 
   }else{
         if(jComboBox2.getSelectedItem().toString().equals("Binario")
                 &&( jComboBox1.getSelectedItem().toString().equals("Decimal"))){///DECIMAL A BINARIO
       String Num=null;//Funciona
  Num=v1.getText();
op CN=new op();
v1.setText(CN.intBinary(new Integer(Num)));
              jComboBox1.setSelectedIndex(4);
             
   }else{
          if(jComboBox2.getSelectedItem().toString().equals("Hexadecimal")
                  &&( jComboBox1.getSelectedItem().toString().equals("Decimal"))){///decimal a hexadecimal
           String Num=null;//Funciona
  Num=v1.getText();
op CN=new op();
v1.setText(CN.intTohex(new Integer(Num)));
 jComboBox1.setSelectedIndex(2);
   }else{
              
                if(jComboBox2.getSelectedItem().toString().equals("Decimal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Decimal"))){///Decimal a decimal
JOptionPane.showMessageDialog(this,"Ya es decimal");
                 jComboBox1.setSelectedIndex(1);
            

                }else{
                       if(jComboBox2.getSelectedItem().toString().equals("Decimal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Binario"))){///binario a decimal

        String Num=null;//Funciona
  Num=v1.getText();
op CN=new op();
v1.setText(CN.bin_dec(new String(Num)));
                    
                    jComboBox1.setSelectedIndex(1);
                }else{
                           if(jComboBox2.getSelectedItem().toString().equals("Hexadecimal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Binario"))){///Binario  a Hexadecimal

        String Num=null;//Funcia
  Num=v1.getText();
op CN=new op();
v1.setText(CN.bin_hex(new String(Num)));
              
                               jComboBox1.setSelectedIndex(2);

                }else{
                           if(jComboBox2.getSelectedItem().toString().equals("Octal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Binario"))){///Binario  a Octal

        String Num=null;//Funciona
  Num=v1.getText();
op CN=new op();
v1.setText(CN.bin_oct(new String(Num)));
                                       jComboBox1.setSelectedIndex(3);

                }else{
                           if(jComboBox2.getSelectedItem().toString().equals("Decimal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Hexadecimal"))){///Hexadecimal  a Decimal

        String Num=null;//Funciona
  Num=v1.getText();
op CN=new op();
v1.setText(CN.hex_dec(new String(Num)));
                                       jComboBox1.setSelectedIndex(1);

                }else{
                           if(jComboBox2.getSelectedItem().toString().equals("Binario")
                        &&( jComboBox1.getSelectedItem().toString().equals("Hexadecimal"))){///Hexadecimal  a Binario

        String Num=null;//Funciona
  Num=v1.getText();
op CN=new op();
v1.setText(CN.hex_bin(new String(Num)));
                                       jComboBox1.setSelectedIndex(4);

                }else{
                           if(jComboBox2.getSelectedItem().toString().equals("Hexadecimal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Octal"))){///Octal  a Hexadecimal

        String Num=null;//Funciona
  Num=v1.getText();
op CN=new op();
v1.setText(CN.hex_oct(new String(Num)));
                                       jComboBox1.setSelectedIndex(2);

                }else{
                           if(jComboBox2.getSelectedItem().toString().equals("Binario")
                        &&( jComboBox1.getSelectedItem().toString().equals("Octal"))){///octal a binario
       
        String Num=null;//Funciona
  Num=v1.getText();
op CN=new op();
v1.setText(CN.oct_bin(new String(Num)));
                                       jComboBox1.setSelectedIndex(4);

                }else{
                           if(jComboBox2.getSelectedItem().toString().equals("Decimal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Octal"))){///octal a Decimal
       
        String Num=null;//Funciona
  Num=v1.getText();
op CN=new op();
v1.setText(CN.oct_dec(new String(Num)));
                                       jComboBox1.setSelectedIndex(1);

                }else{
                           if(jComboBox2.getSelectedItem().toString().equals("Hexadecimal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Octal"))){///octal a Hexadecimal
       
        String Num=null;//Funciona
  Num=v1.getText();
op CN=new op();
v1.setText(CN.oct_hex(new String(Num)));
                                       jComboBox1.setSelectedIndex(2);

                }else{
                               if(jComboBox2.getSelectedItem().toString().equals("Octal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Octal"))){///Octal a octal
JOptionPane.showMessageDialog(this,"Ya es un octal");
                 jComboBox1.setSelectedIndex(3);
            

                }else{
                               if(jComboBox2.getSelectedItem().toString().equals("Hexadecimal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Hexadecimal"))){///Hexadecimal a Hexadecimal
JOptionPane.showMessageDialog(this,"Ya es  Hexadecimal");
                 jComboBox1.setSelectedIndex(2);
            

                }else{
                               if(jComboBox2.getSelectedItem().toString().equals("Binario")
                        &&( jComboBox1.getSelectedItem().toString().equals("Binario"))){///Binario a Binario
JOptionPane.showMessageDialog(this,"Ya es Binario ");
                 jComboBox1.setSelectedIndex(4);
            

                }
                 
                  /*  ///funciona pero marca error por el tipo de dato
                     if(jComboBox2.getSelectedItem().toString().equals("Hexadecimal")
                             &&( jComboBox1.getSelectedItem().toString().equals("Binario"))){///decimal octal
   conv.setNu(Integer.valueOf(v1.getText()));
   v1.setText(String.valueOf(conv.binario_hexadecimal()));
                         
                          jComboBox1.setSelectedIndex(4);

                          
                     }else{
                         
                     if(jComboBox2.getSelectedItem().toString().equals("Octal")
                             &&( jComboBox1.getSelectedItem().toString().equals("Binario"))){///decimal octal
   conv.setNu(Integer.valueOf(v1.getText()));
                         v1.setText(String.valueOf(conv.binario_octal()));
                         
                          jComboBox1.setSelectedIndex(4);

                          
                     }
                    
                    
                          
                                                     
                     }*/                                                      }
                                                                             }
                                                                                          }
                                                                                       }
                                                                               }        
                                                                      }
                               
                               
                                                                  }
                                                           }
                                              }
                       }
                    
                }
              
              
              
          }     
             
             
             
             
             
         }
   }
         
        }

        /**/
        
            if(jComboBox2.getSelectedItem().toString().equals("Sistema Numerico")
                        &&( jComboBox1.getSelectedItem().toString().equals("Sistema Numerico"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el valor 2");
                 jComboBox1.setSelectedIndex(0);     
                 jComboBox2.setSelectedIndex(0);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Sistema Numerico")
                        &&( jComboBox1.getSelectedItem().toString().equals("Decimal"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el valor 2");
                 jComboBox1.setSelectedIndex(1);     
                 jComboBox2.setSelectedIndex(0);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Sistema Numerico")
                        &&( jComboBox1.getSelectedItem().toString().equals("Hexadecimal"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el valor 2");
                 jComboBox1.setSelectedIndex(2);     
                 jComboBox2.setSelectedIndex(0);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Sistema Numerico")
                        &&( jComboBox1.getSelectedItem().toString().equals("Octal"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el valor 2");
                 jComboBox1.setSelectedIndex(3);     
                 jComboBox2.setSelectedIndex(0);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Sistema Numerico")
                        &&( jComboBox1.getSelectedItem().toString().equals("Binario"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el valor 2");
                 jComboBox1.setSelectedIndex(4);     
                 jComboBox2.setSelectedIndex(0);     

                }
            }
         
                                }
                
                
                
            
            }
                
                if(jComboBox2.getSelectedItem().toString().equals("Decimal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Sistema Numerico"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el valor 1");
                 jComboBox1.setSelectedIndex(0);     
                 jComboBox2.setSelectedIndex(1);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Hexadecimal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Sistema Numerico"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el valor 1");
                 jComboBox1.setSelectedIndex(0);     
                 jComboBox2.setSelectedIndex(2);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Sistema Numerico")
                        &&( jComboBox1.getSelectedItem().toString().equals("Octal"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el valor 1");
                 jComboBox1.setSelectedIndex(0);     
                 jComboBox2.setSelectedIndex(3);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Binario")
                        &&( jComboBox1.getSelectedItem().toString().equals("Sistema Numerico"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el valor 1");
                 jComboBox1.setSelectedIndex(0);     
                 jComboBox2.setSelectedIndex(4);     
                    
                }
                    
            }
                          
                                }
                
                    
                }
                            
            }
            }catch(Exception e){///es una excepcion
         JOptionPane.showMessageDialog(this,"El dato introducido es incorrecto");
    
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 //ver como reinciar un jbox    
        jComboBox1.setSelectedIndex(0);
        
        jComboBox2.setSelectedIndex(0);
        
        jComboBox3.setSelectedIndex(0);
         
        
        v1.setText(null);          
           v2.setText(null);               
       v3.setText(null);
       
                    JOptionPane.showMessageDialog(null,"Listo,para ser usado");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();        //detiene el jframe
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
        if(jComboBox2.getSelectedItem().toString().equals("Decimal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Decimal"))){///suma decimal
     
  int su1=Integer.valueOf(v1.getText());     
  int su2=Integer.valueOf(v2.getText());//sacar es getText   
 String res;                 
  res=String.valueOf(su1+su2);
              v3.setText(res);///setText meter
  
 }else{
     
      if(jComboBox2.getSelectedItem().toString().equals("Binario")
                        &&( jComboBox1.getSelectedItem().toString().equals("Binario"))){///suma Binario
String Num1=null;
         String Num=null;//Funciona
  Num=v1.getText();
  Num1=v2.getText();
op CN=new op();
v3.setText(CN.SumaB(new String(Num),new String(Num1)));///mando los dos datos a suma los  cuales toman 
//la posicion de string a que es num y string b que es num1
     
     
      }else{
     
      if(jComboBox2.getSelectedItem().toString().equals("Octal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Octal"))){///suma octal
///base 8 de octal
     String Num1=null;
         String Num=null;//Funciona
  Num=v1.getText();
  Num1=v2.getText();
op CN=new op();
v3.setText(CN.SumaO(new String(Num),new String(Num1)));
          
          
          
          
          
      }else{
          
          
           if(jComboBox2.getSelectedItem().toString().equals("Hexadecimal")
                        &&( jComboBox1.getSelectedItem().toString().equals("Hexadecimal"))){///Binario a Binario
  String Num1=null;
         String Num=null;//Funciona
  Num=v1.getText();
  Num1=v2.getText();
op CN=new op();
v3.setText(CN.SumaH(new String(Num),new String(Num1)));
     ////CHECAR
          
          
          
          
          
      }else{ if(jComboBox2.getSelectedItem().toString().equals("Sistema Numerico")
                        &&( jComboBox3.getSelectedItem().toString().equals("Sistema Numerico"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el resultado");
                 jComboBox3.setSelectedIndex(0);     
                 jComboBox2.setSelectedIndex(0);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Sistema Numerico")
                        &&( jComboBox3.getSelectedItem().toString().equals("Decimal"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el resultado");
                 jComboBox3.setSelectedIndex(1);     
                 jComboBox2.setSelectedIndex(0);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Sistema Numerico")
                        &&( jComboBox3.getSelectedItem().toString().equals("Hexadecimal"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el resultado");
                 jComboBox3.setSelectedIndex(2);     
                 jComboBox2.setSelectedIndex(0);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Sistema Numerico")
                        &&( jComboBox3.getSelectedItem().toString().equals("Octal"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el resultado");
                 jComboBox3.setSelectedIndex(3);     
                 jComboBox2.setSelectedIndex(0);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Sistema Numerico")
                        &&( jComboBox3.getSelectedItem().toString().equals("Binario"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el resultado");
                 jComboBox3.setSelectedIndex(4);     
                 jComboBox2.setSelectedIndex(0);     

                }
            }
         
                                }
                
                
                }
            
            }     

                }
           }
          
      }
          
          
      }
 
                if(jComboBox2.getSelectedItem().toString().equals("Decimal")
                        &&( jComboBox3.getSelectedItem().toString().equals("Sistema Numerico"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el resultado");
                 jComboBox3.setSelectedIndex(0);     
                 jComboBox2.setSelectedIndex(1);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Hexadecimal")
                        &&( jComboBox3.getSelectedItem().toString().equals("Sistema Numerico"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el resultado");
                 jComboBox3.setSelectedIndex(0);     
                 jComboBox2.setSelectedIndex(2);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Octal")
                        &&( jComboBox3.getSelectedItem().toString().equals("Sistema Numerico"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el resultado");
                 jComboBox3.setSelectedIndex(0);     
                 jComboBox2.setSelectedIndex(3);     

                }else{
                if(jComboBox2.getSelectedItem().toString().equals("Binario")
                        &&( jComboBox3.getSelectedItem().toString().equals("Sistema Numerico"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico para el resultado");
                 jComboBox3.setSelectedIndex(0);     
                 jComboBox2.setSelectedIndex(4);     
                
                
            }
                }
                }
  }

    }catch(Exception e){
  JOptionPane.showMessageDialog(this,"Datos erroneos");
}
                      

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 /*if(jComboBox3.getSelectedItem().toString().equals("Decimal")&&
                ( jComboBox2.getSelectedItem().toString().equals("Octal"))){///Octal a Decimal 
    String Num=null;//FUNCIONA
  Num=v3.getText();
op CN=new op();
v3.setText(CN.oct_dec(new String(Num)));
 jComboBox1.setSelectedIndex(1);
   }*/try{
   if(jComboBox3.getSelectedItem().toString().equals("Octal")&&
                ( jComboBox2.getSelectedItem().toString().equals("Decimal"))){///decimal A octal 
    String Num=null;//FUNCIONA
  Num=v3.getText();
op CN=new op();
v3.setText(CN.intToOctal(new Integer(Num)));
 jComboBox3.setSelectedIndex(3);
   }else{
         if(jComboBox3.getSelectedItem().toString().equals("Binario")
                 &&( jComboBox2.getSelectedItem().toString().equals("Decimal"))){///DECIMAL A BINARIO
       String Num=null;//Funciona
  Num=v3.getText();
op CN=new op();
v3.setText(CN.intBinary(new Integer(Num)));
              jComboBox3.setSelectedIndex(4);
             
   }else{
          if(jComboBox3.getSelectedItem().toString().equals("Hexadecimal")
                  &&( jComboBox2.getSelectedItem().toString().equals("Decimal"))){///decimal a hexadecimal
           String Num=null;//Funciona
  Num=v3.getText();
op CN=new op();
v3.setText(CN.intTohex(new Integer(Num)));
 jComboBox3.setSelectedIndex(2);
   }else{
              
                if(jComboBox3.getSelectedItem().toString().equals("Decimal")
                        &&( jComboBox2.getSelectedItem().toString().equals("Decimal"))){///Decimal a decimal
JOptionPane.showMessageDialog(this,"Ya es decimal");
                 jComboBox3.setSelectedIndex(1);
            

                }else{
                       if(jComboBox3.getSelectedItem().toString().equals("Decimal")
                        &&( jComboBox2.getSelectedItem().toString().equals("Binario"))){///binario a decimal

        String Num=null;//Funciona
  Num=v3.getText();
op CN=new op();
v3.setText(CN.bin_dec(new String(Num)));
                    
                    jComboBox3.setSelectedIndex(1);
                }else{
                           if(jComboBox3.getSelectedItem().toString().equals("Hexadecimal")
                        &&( jComboBox2.getSelectedItem().toString().equals("Binario"))){///Binario  a Hexadecimal

        String Num=null;//Funcia
  Num=v3.getText();
op CN=new op();
v3.setText(CN.bin_hex(new String(Num)));
              
                               jComboBox3.setSelectedIndex(2);

                }else{
                           if(jComboBox3.getSelectedItem().toString().equals("Octal")
                        &&( jComboBox2.getSelectedItem().toString().equals("Binario"))){///Binario  a Octal

        String Num=null;//Funciona
  Num=v3.getText();
op CN=new op();
v3.setText(CN.bin_oct(new String(Num)));
                                       jComboBox3.setSelectedIndex(3);

                }else{
                           if(jComboBox3.getSelectedItem().toString().equals("Decimal")
                        &&( jComboBox2.getSelectedItem().toString().equals("Hexadecimal"))){///Hexadecimal  a Decimal

        String Num=null;//Funciona
  Num=v3.getText();
op CN=new op();
v3.setText(CN.hex_dec(new String(Num)));
                                       jComboBox3.setSelectedIndex(1);

                }else{
                           if(jComboBox3.getSelectedItem().toString().equals("Binario")
                        &&( jComboBox2.getSelectedItem().toString().equals("Hexadecimal"))){///Hexadecimal  a Binario

        String Num=null;//Funciona
  Num=v3.getText();
op CN=new op();
v3.setText(CN.hex_bin(new String(Num)));
                                       jComboBox3.setSelectedIndex(4);

                }else{
                           if(jComboBox3.getSelectedItem().toString().equals("Hexadecimal")
                        &&( jComboBox2.getSelectedItem().toString().equals("Octal"))){///Octal  a Hexadecimal

        String Num=null;//Funciona
  Num=v3.getText();
op CN=new op();
v3.setText(CN.hex_oct(new String(Num)));
                                       jComboBox3.setSelectedIndex(2);

                }else{
                           if(jComboBox3.getSelectedItem().toString().equals("Binario")
                        &&( jComboBox2.getSelectedItem().toString().equals("Octal"))){///octal a binario
       
        String Num=null;//Funciona
  Num=v3.getText();
op CN=new op();
v3.setText(CN.oct_bin(new String(Num)));
                                       jComboBox3.setSelectedIndex(4);

                }else{
                           if(jComboBox3.getSelectedItem().toString().equals("Decimal")
                        &&( jComboBox2.getSelectedItem().toString().equals("Octal"))){///octal a Decimal
       
        String Num=null;//Funciona
  Num=v3.getText();
op CN=new op();
v3.setText(CN.oct_dec(new String(Num)));
                                       jComboBox3.setSelectedIndex(1);

                }else{
                           if(jComboBox3.getSelectedItem().toString().equals("Hexadecimal")
                        &&( jComboBox2.getSelectedItem().toString().equals("Octal"))){///octal a Hexadecimal
       
        String Num=null;//Funciona
  Num=v3.getText();
op CN=new op();
v3.setText(CN.oct_hex(new String(Num)));
                                       jComboBox3.setSelectedIndex(2);

                }else{
                               if(jComboBox3.getSelectedItem().toString().equals("Octal")
                        &&( jComboBox2.getSelectedItem().toString().equals("Octal"))){///Octal a octal
JOptionPane.showMessageDialog(this,"Ya es un octal");
                 jComboBox3.setSelectedIndex(3);
            

                }else{
                               if(jComboBox3.getSelectedItem().toString().equals("Hexadecimal")
                        &&( jComboBox2.getSelectedItem().toString().equals("Hexadecimal"))){///Hexadecimal a Hexadecimal
JOptionPane.showMessageDialog(this,"Ya es un Hexadecimal");
                 jComboBox3.setSelectedIndex(3);
            

                }else{
                               if(jComboBox3.getSelectedItem().toString().equals("Binario")
                        &&( jComboBox2.getSelectedItem().toString().equals("Binario"))){///Binario a Binario
JOptionPane.showMessageDialog(this,"Ya es un octal");
                 jComboBox3.setSelectedIndex(3);
            

                }
                 
                  /*  ///funciona pero marca error por el tipo de dato
                     if(jComboBox2.getSelectedItem().toString().equals("Hexadecimal")
                             &&( jComboBox1.getSelectedItem().toString().equals("Binario"))){///decimal octal
   conv.setNu(Integer.valueOf(v1.getText()));
   v1.setText(String.valueOf(conv.binario_hexadecimal()));
                         
                          jComboBox1.setSelectedIndex(4);

                          
                     }else{
                         
                     if(jComboBox2.getSelectedItem().toString().equals("Octal")
                             &&( jComboBox1.getSelectedItem().toString().equals("Binario"))){///decimal octal
   conv.setNu(Integer.valueOf(v1.getText()));
                         v1.setText(String.valueOf(conv.binario_octal()));
                         
                          jComboBox1.setSelectedIndex(4);

                          
                     }
                    
                    
                          
                                                     
                     }*/                                                      }
                                                                             }
                                                                                          }
                                                                                       }
                                                                               }        
                                                                      }
                               
                               
                                                                  }
                                                           }
                                              }
                       }
                    
                }
              
              
              
          }     
             
             
             
             
             
         }
   }
         
        }
    }catch(Exception e){
 JOptionPane.showMessageDialog(this,"Datos erroneos");
    }
                            //aa

                           if(jComboBox3.getSelectedItem().toString().equals("Sistema Numerico")
                        &&( jComboBox2.getSelectedItem().toString().equals("Sistema Numerico"))){///octal a binario
       
JOptionPane.showMessageDialog(this,"Seleccione un tipo de sistema numerico");
                 jComboBox3.setSelectedIndex(0);     
                 jComboBox2.setSelectedIndex(0);     
                }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField v1;
    private javax.swing.JTextField v2;
    private javax.swing.JTextField v3;
    // End of variables declaration//GEN-END:variables
}
